name: Latest Build

on:
  push:
    branches: [ master, pre ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal


    - name: Deploy Rainbow.Core to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Rainbow.Core/Rainbow.Core.csproj
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_KEY}}

    - name: Deploy Rainbow.Graphics to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Rainbow.Graphics/Rainbow.Graphics.csproj
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_KEY}}

    - name: Deploy Rainbow.Physics to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Rainbow.Physics/Rainbow.Physics.csproj
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_KEY}}

    - name: Deploy Rainbow.State to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Rainbow.State/Rainbow.State.csproj
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_KEY}}

    - name: Deploy Rainbow to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: Rainbow/Rainbow.csproj
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_KEY}}
